### ISSUE TITLE
纯粹多库时不支持@DS切换数据

### ISSUE THREAD

**Issue by 1034323716** [baomidou/dynamic-datasource-spring-boot-starter#101]
在启动的时候就提示为单数据源，且@DS标注不起作用，使用的依然为主数据源。
配置
```
dynamic:
      primary: OPDB
      druid:
        max-active: 10
        min-idle: 2
        validation-query: select 1
        validation-query-timeout: 2000
      strict: true
      datasource:
        OPDB:
          url: xxx
          driver-class-name: com.mysql.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
        RegisterExtDB:
          url: xxx
          driver-class-name: com.mysql.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
```
