### ISSUE TITLE
could not find schema or data file classpath:db/schema-h2.sql

### ISSUE THREAD

**Issue by bosshe** [baomidou/dynamic-datasource-spring-boot-starter#112]
# Enviroment

JDK Version(required): 
1.8

SpringBoot Version(required): 
2.2.0
Starter Version(required):
2.5.6
Mybatis-plus Version:
3.2.0
# Describe
数据源配置如下：
```
spring:
  datasource:
    dynamic:
      primary: test
      datasource:
        test:
          driver-class-name: org.h2.Driver
          schema: classpath:db/schema-h2.sql
          data: classpath:db/data-h2.sql
          url: jdbc:h2:mem:test
          username: root
          password: test
```
启动项目时提示找不到 schema-h2.sql 和 data-h2.sql 文件。

解决方案：去掉 “classpath:”。

Expected Result: 
使用"classpath:"前缀也可以加载到数据文件。
Actual Result:  
相同的配置在 Mybatis-plus 中可以找到相应的 sql 文件，但是在 dynamic-datasource-spring-boot-starter 却报错。
# Steps to reproduce

- Step 1 

- Step 2 

- Step 3
