### ISSUE TITLE
配置多数据源成功，但无法访问druid的web控制台

### ISSUE THREAD

**Issue by bearxsh** [baomidou/dynamic-datasource-spring-boot-starter#154]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.1.6.RELEASE

Starter Version(required):3.0.0

# Describe
配置多数据源成功，但无法访问druid的web控制台。http://localhost:8080/druid/index.html 无法访问

# 相关配置
```
spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,slf4j
      stat-view-servlet:
        loginUsername: admin
        loginPassword: admin#2018
        url-pattern: /druid/*
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
    dynamic:
      druid:
        max-active: 100
        min-idle: 10
        initial-size: 5
        max-wait: 60000
        validation-query: select 1+1
        validation-query-timeout: 10
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        pool-prepared-statements: true
        filters: stat,wall,slf4j

      primary: one
      datasource:
        one:
          url: jdbc:mysql://mysql:3306/one?autoReconnect=true&characterEncoding=utf-8&serverTimezone=CTT
          username: admin
          password: admin
          driver-class-name: com.mysql.cj.jdbc.Driver
        two:
          url: jdbc:mysql://mysql:3306/two?autoReconnect=true&characterEncoding=utf-8&serverTimezone=CTT
          username: admin
          password: admin
          driver-class-name: com.mysql.cj.jdbc.Driver
```
