### ISSUE TITLE
3.0.0版本数据源名称不包含下划线无法正常工作

### ISSUE THREAD

**Issue by peihuanhuan** [baomidou/dynamic-datasource-spring-boot-starter#185]
# Enviroment

JDK Version(required): 

openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)

SpringBoot Version(required): 
2.2.6.RELEASE

Starter Version(required):
com.baomidou:mybatis-plus-boot-starter:3.3.1
com.baomidou:dynamic-datasource-spring-boot-starter:3.0.0

# Describe

datasource 中，若数据源名字如果不含下划线，在mapper中使用 @DS 时将一直使用默认数据源。
如 @DS("hello") 将不会使用对应的数据源， 而 @DS("hello_world") 能正常使用

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by huayanYu** [comment]
贴出你的配置。

**Comment by peihuanhuan** [comment]
```yaml
spring:
  datasource:
    dynamic:
      primary: sail_platform
      datasource:
        pass:
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/paas
        nebula_meeting:
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/saas
        sail_platform:
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/sail_platform_over2

```
nebula_meeting数据源能正常切换 ，paas数据源不能切换，会使用默认数据源。
如果将 paas 改成 sail_pass 能正常切换
