### ISSUE TITLE
从库只可读的情况下会报错

### ISSUE THREAD

**Issue by remember-5** [baomidou/dynamic-datasource-spring-boot-starter#190]
# Enviroment
macOS 10.14.6
JDK Version(required): 
1.8
SpringBoot Version(required): 
2.2.0
Starter Version(required):
3.0.0
# Describe
Mysql Version `8.0.19`
MybatisPlus Version `3.2.0`

主库可读可写，从库只可读的情况下会报错。无法执行sql

异常如下
```
 Cause: java.sql.SQLException: The MySQL server is running with the --read-only option so it cannot execute this statement
; uncategorized SQLException; SQL state [HY000]; error code [1290]; The MySQL server is running with the --read-only option so it cannot execute this statement; nested exception is java.sql.SQLException: The MySQL server is running with the --read-only option so it cannot execute this statement
```

Expected Result: 

Actual Result:  

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by remember-5** [comment]
## 补充
1. 数据库的配置如下：
```
datasource:
    dynamic:
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: IntegralHikariCP
      primary: base
      datasource:
        base:
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${mysql-master.url}:3306/cloud_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
        business:
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${mysql-master.url}:3306/business_1?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
        business_slave:
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://${mysql-slave.url}:3306/business_1?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
          hikari: # 以下参数针对每个库可以重新设置hikari参数
            is-read-only: true
```
在`business_slave`重写了`hikari`的is-read-only的属性为true

以上测下来还是会报错
