### ISSUE TITLE
datasource需要遵守hikari的配置

### ISSUE THREAD

**Issue by carter-ya** [baomidou/dynamic-datasource-spring-boot-starter#274]
# Enviroment

JDK Version(required):  1.8

SpringBoot Version(required):  2.1.4

dynamic-datasource-spring-boot-starter Version(required): 3.2.0

druid Version(optional):

# Describe

```yaml
        slave:
          url: ${spring.datasource.dynamic.datasource.master.url}
          username: ${spring.datasource.dynamic.datasource.master.username}
          password: ${spring.datasource.dynamic.datasource.master.password}
          type: ${spring.datasource.dynamic.datasource.master.type}
          hikari:
            pool-name: OthersSlaveDB
```
不遵守配置的hikari配置（配置的连接池名称不生效）

```java
public class HikariDataSourceCreator {

    private HikariCpConfig hikariCpConfig;

    public DataSource createDataSource(DataSourceProperty dataSourceProperty) {
        HikariConfig config = dataSourceProperty.getHikari().toHikariConfig(hikariCpConfig);
        config.setUsername(dataSourceProperty.getUsername());
        config.setPassword(dataSourceProperty.getPassword());
        config.setJdbcUrl(dataSourceProperty.getUrl());
        config.setPoolName(dataSourceProperty.getPoolName());
        String driverClassName = dataSourceProperty.getDriverClassName();
        if (!StringUtils.isEmpty(driverClassName)) {
            config.setDriverClassName(driverClassName);
        }
        return new HikariDataSource(config);
    }
}
```
