### ISSUE TITLE
如何使用druid的sql打印

### ISSUE THREAD

**Issue by yl-yue** [baomidou/dynamic-datasource-spring-boot-starter#336]
# Enviroment

JDK Version(required): 11

SpringBoot Version(required): 2.3.5

dynamic-datasource-spring-boot-starter Version(required):3.3.1

druid Version(optional):1.1.20

# Describe what happened

Expected Result:

如何使用druid的sql打印？

druid原生配置：
```yml
spring:
  datasource:
      druid:
        filter:
          slf4j:
            enabled: true
            statement-prepare-after-log-enabled: false
            statement-execute-query-after-log-enabled: false
            statement-executable-sql-log-enable: true
logging:
  level:
    druid.sql.Statement: DEBUG
```

尝试结合dynamic-datasource的配置：

```yml
spring:
  datasource:
    dynamic:
      druid:
        filter:
          slf4j:
            enabled: true
            statement-prepare-after-log-enabled: false
            statement-execute-query-after-log-enabled: false
            statement-executable-sql-log-enable: true
#        stat:
#          log-slow-sql: true
#        filters: 
        slf4j:
          enable: true
          statement-executable-sql-log-enable: true
      datasource:
        aaa:
          url: jdbc:mysql://192.168.0.*:900/table?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
          username: root
          password: 123
          druid:
            slf4j:
              enable: true
              statement-executable-sql-log-enable: true
```

Actual Result:

以上配置都是无效的，并不会打印sql

**Comment by yl-yue** [comment]
已找到正确的配置如下：
```yml
spring:
  datasource:
    dynamic:
      druid:
        filters: slf4j
        slf4j:
          enable: true
          statement-executable-sql-log-enable: true
      datasource:
        aaa:
          url: jdbc:mysql://192.168.0.*:900/table?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
          username: root
          password: 123
```

**Comment by yl-yue** [comment]
每个库单独配置不生效，不覆盖父类配置？
```yml
spring:
  datasource:
    dynamic:
      druid:
        filters: slf4j
        slf4j:
          enable: true
          statement-executable-sql-log-enable: true
      datasource:
        aaa:
          url: jdbc:mysql://192.168.0.*:900/aaa?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
          username: aaa
          password: aaa
        bbb:
          url: jdbc:mysql://192.168.0.*:900/bbb?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
          username: bbb
          password: bbb
          # 以下配置不生效
          druid:
            slf4j:
              enable: false
              statement-executable-sql-log-enable: false
```

同时建议`dynamic-datasource`采用与`druid-spring-boot-starter`相似的配置结构，降低学习成本。
如druid拦截器配置：
```yml
spring:
  datasource:
      druid:
        filter:
          slf4j:
            enabled: true
            statement-prepare-after-log-enabled: false
            statement-execute-query-after-log-enabled: false
            statement-executable-sql-log-enable: true
logging:
  level:
    druid.sql.Statement: DEBUG
```
