### ISSUE TITLE
如果一个数据源挂掉后，能够自动切换到另外一个数据源吗？

### ISSUE THREAD

**Issue by developers-youcong** [baomidou/dynamic-datasource-spring-boot-starter#347]
# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.1.2

dynamic-datasource-spring-boot-starter Version(required):2.5.4

druid Version(optional):1.1.13

# Describe what happened

Expected Result:

如果一个数据源挂掉后，能够自动切换到另外一个数据源吗？任意一个数据源都会实时数据同步。

Actual Result:

看官网上，没有这相关的信息。

我的代码配置:
```
#spring:
spring:
  datasource:
    dynamic:
      primary: db1 #设置默认的数据源,默认值为master
      datasource:
        db1:  #数据源db1
          # 数据库驱动
          driver-class-name: com.mysql.cj.jdbc.Driver
          # 数据库URL
          url: jdbc:mysql://127.0.0.1:3306/sys-saas?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
          # 数据库访问用户
          username: root
          # 数据库访问密码
          password: 123456
       db2:  #数据源db1
          # 数据库驱动
          driver-class-name: com.mysql.cj.jdbc.Driver
          # 数据库URL
          url: jdbc:mysql://127.0.0.1:3307/sys-saas?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
          # 数据库访问用户
          username: root
          # 数据库访问密码
          password: 123456
      # 指定数据库连接池类型
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        #  初始化连接数
        initial-size: 3
        #  最大连接池数量
        max-active: 8
        # 连接池中的最小空闲连接数
        min-idle: 3
        # 获取连接时最大等待时间
        max-wait: 5000
        # 是否缓存preparedStatement
        pool-prepared-statements: true
        # 每个连接上PSCache的大小
        max-pool-prepared-statement-per-connection-size: 20
        # 验证连接是否有效的时间周期
        time-between-eviction-runs-millis: 90000
        # 指定一个空闲连接最少空闲多久后可被清除
        min-evictable-idle-time-millis: 1800000
        # 验证连接的有效性
        test-while-idle: true
        # 获取连接时候验证，会影响性能
        test-on-borrow: false
        # 在连接归还到连接池时是否测试该连接
        test-on-return: false
        # 监控信息界面配置
        stat-view-servlet:
          # 是否开启监控信息界面
          enabled: true
          # 路由匹配
          url-pattern: /druid/*
        # 配置扩展插件
        filter:
          # 开启慢SQL监控
          stat:
            log-slow-sql: true
            slow-sql-millis: 1000
            merge-sql: fals
          # 配置过滤器参数
          wall:
            config:
              multi-statement-allow: true
```
