### ISSUE TITLE
全局配置druid时，如何 stat-view-servlet配置不生效

### ISSUE THREAD

**Issue by jrt324** [baomidou/dynamic-datasource-spring-boot-starter#364]
想访问一下druid的监控页面，application.yml中全局配置druid时，  stat-view-servlet配置不生效，
com.baomidou.dynamic.datasource.spring.boot.autoconfigure.druid.DruidConfig类下面并没有statViewServlet配置字段

```
spring:
  datasource:
    dynamic:
      druid:
         initial-size: 5
          ........
          stat-view-servlet:
             enabled: true
```

# Enviroment

JDK Version(required): 1.8

SpringBoot Version(required): 2.3

dynamic-datasource-spring-boot-starter Version(required): 3.3.2

druid Version(optional): 1.1.22

# Describe what happened

Expected Result:
按理说如果配置了druid.stat-view-servlet.enabled=true 应该就能在http://localhost:8081/druid/sql.html 查看监控页面了

Actual Result:
没有显示

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3
