### ISSUE TITLE
测试过程中，DynamicRoutingDataSource.determineDataSource()的执行先于DynamicDataSourceAnnotationInterceptor.invoke()

### ISSUE THREAD

**Issue by NGLSL** [baomidou/dynamic-datasource-spring-boot-starter#410]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required):  
openjdk version "11.0.13" 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8 (build 11.0.13+8, mixed mode)

SpringBoot Version(required): 2.6.1

dynamic-datasource-spring-boot-starter Version(required):3.5.0

druid Version(optional):

# Describe what happened

Expected Result:

希望能切换到ServiceImpl类上@DS注解指定的数据源。

Actual Result:

未能切换到指定的数据源，而走的是默认数据源。

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

发送HTTP请求，Controller调用不同数据源的Service

```Java
ServiceA serviceA;
ServiceB serviceB;

public Object sayHello() {
  serviceA.xxx();
  serviceB.xxx();
}

@DS("serviceA")
public class ServiceA{
    ...
}
@DS("serviceB")
public class ServiceB{
    ...
}
```

- Step 2 

yml:

```yaml
spring:
  datasource:
    dynamic:
      strict: true
      primary:  serviceA
      aop:
        enabled: true
        allowed-public-only: false
      datasource:
        serviceA:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: xxx
          password: xxx
          url: xxx
          type: com.zaxxer.hikari.HikariDataSource
        serviceB:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: xxx
          password: xxx
          url: xxx
          type: com.zaxxer.hikari.HikariDataSource
```

- Step 3 

实际测试过程中，一直走的都是默认的数据源，没有走ServiceImpl上指定的数据源。

在Debug代码的过程中，`com.baomidou.dynamic.datasource.DynamicRoutingDataSource#determineDataSource`的代码块，比`com.baomidou.dynamic.datasource.aop.DynamicDataSourceAnnotationInterceptor#invoke`的代码块先执行。

简单点说，切换数据指定数据源的动作，比获取数据源的要先，从而导致`com.baomidou.dynamic.datasource.DynamicRoutingDataSource#getDataSource`的代码块中，一直获取默认数据源。

![image](https://user-images.githubusercontent.com/40338580/146957463-3f3db42a-916f-4428-ba62-a7a3a1d6e438.png)

![image](https://user-images.githubusercontent.com/40338580/146957738-0c1e59b7-6c74-4270-93bd-8870d24cc200.png)
