### ISSUE TITLE
集成shardingJDBC，shardingJDBC不生效。

### ISSUE THREAD

**Issue by copi111** [baomidou/dynamic-datasource-spring-boot-starter#486]
JDK Version(required): openjdk version "17.0.3"

SpringBoot Version(required):  3.0.0

dynamic-datasource-spring-boot-starter Version(required):3.6.1

druid Version(optional):1.2.6

shardingsphere-jdbc-core-spring-boot-starter Versuib : 5.1.0

Expected Result:
项目，正常运行。
查询分表时，不生效。

```yaml
  spring:
  application:
    name: manage-service
  main:
    allow-bean-definition-overriding: true
  #动态数据源
  datasource:
    dynamic:
      primary: read
      strict: false
      datasource:
        write:
          url:  xxx
          username: xxx
          password: xxx
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
        read:
          url: xxx
          username:xxx
          password: xxx
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.alibaba.druid.pool.DruidDataSource
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: master0,slave0
      master0:
        url: xxx
        username: xxx
        password: xxx
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
      slave0:
        url: xxxx
        username: xxx
        password: xxx
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
    rules:
      readwrite-splitting:
        load-balancers:
          round_robin:
            type: ROUND_ROBIN
        data-sources:
          prds:
            write-data-source-name: master0
            read-data-source-names: slave0
            load-balancer-name: round_robin
      sharding:
        sharding-algorithms:
          my-shard-inline:
            type: INLINE
            props:
              algorithm-expression: user_$->{open_id % 3}
        tables:
          user:
            actual-data-nodes: prds.user_$->{[0]}
            table-strategy:
              standard:
                sharding-column: open_id
                sharding-algorithm-name: my-shard-inline

```

Actual Result:

```
Creating a new SqlSession
SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@dc82abb] was not registered for synchronization because synchronization is not active
JDBC Connection [com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl@67a3013c] will not be managed by Spring
==>  Preparing: SELECT id,`name`,open_id,service_id FROM sys.user
==> Parameters: 
<==    Columns: id, name, open_id, service_id
<==        Row: 06919a8534a35bcf917cfbc27fd2e770, 张三, 100, 0a79b32b999c42129b97b11484d030dd
<==        Row: 24996cc97ba813681588a63e0e1a3e40, 张三, 100, cab42f8e698045b29d119119b89fe690
<==        Row: 996664d781a35dc075b78a1ee5e9e695, 张三, 100, 5e56e71266ad440e9fcb0818f40e6c19
<==      Total: 3
Closing non transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@dc82abb]

```
