### ISSUE TITLE
使用@DSTransactional注解，slave库会触发表锁

### ISSUE THREAD

**Issue by zhujiebing** [baomidou/dynamic-datasource-spring-boot-starter#516]
Please fill it out carefully, or it will be closed.
请认真填写，不然会直接关闭。

# Enviroment

JDK Version(required):  17

SpringBoot Version(required): 2.6.8

dynamic-datasource-spring-boot-starter Version(required): 3.5.1

druid Version(optional): 
hikariCp: spring boot默认版本

# Describe what happened
麻烦看一下这个问题，我在service方法使用@DSTransactional，对两个库的表进行update，master库(mySql)不会锁表，slave库(Sqlserver)会锁表

```java
@Mapper
public interface ModelPubMapper extends BaseMapper<ModelPub> {

}
```

```java
@DS("mdm")
@Mapper
public interface ReceiptMapper extends BaseMapper<Receipt> {
}
```

```java
@DSTransactional
    public void mockReceipt() {
        while (true) {
           // master库update，modelId是主键
            modelPubMapper.update(null,new LambdaUpdateWrapper<ModelPub>()
                    .set(ModelPub::getModelName,"客商模型").eq(ModelPub::getModelId,"a3d6afe546ac4cd4b0e105562d94740c"));

           // slave库update，receiptId是主键
            receiptMapper.update(null,new LambdaUpdateWrapper<Receipt>()
                    .set(Receipt::getUserId,"dev").eq(Receipt::getReceiptId,105770));
        }
    }
```

```yml
# 多数据源配置
spring:
  main:
    allow-circular-references: true
  datasource:
    dynamic:
      primary: foudation
      strict: false 
      hikari:
        min-idle: 2          
      datasource:    
        foudation:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.20.201.120:3306/dc_foundation?characterEncoding=utf8&useAffectedRows=true&useSSL=false&serverTimezone=GMT%2B8
          username: root
          password: xxxx
        mdm:
          url: jdbc:sqlserver://10.126.13.6:1433;databaseName=mdm_data;integratedSecurity=false
          username: sa
          password: xxxx
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.20.201.120:3306/dc_foundation?characterEncoding=utf8&useAffectedRows=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: xxxx
```

Expected Result:
master库和slave库进行update都只触发行锁。

Actual Result:
slave库的Receipt表触发了表锁，其它会话无法对这张表进行查询。
master库的mdm_model_pub表在update的时候，其它会话可以正常对这张表进行查询访问。

![7b2d9bd9-5ab8-4e8f-adac-8a2053412453](https://github.com/baomidou/dynamic-datasource-spring-boot-starter/assets/25639514/43008f56-dbc8-4929-86c9-40df9a933b68)

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3
