### ISSUE TITLE
4.1.1 动态添加移除数据源异常

### ISSUE THREAD

**Issue by sam2099** [baomidou/dynamic-datasource-spring-boot-starter#534]
# Enviroment

JDK Version(required): 17

SpringBoot Version(required): 3.1.0

dynamic-datasource-spring-boot-starter Version(required): 4.1.1

druid Version(optional): 无

# Describe what happened
H2数据库，hikari 连接池

参照文档https://www.kancloud.cn/tracy5546/dynamic-datasource/2268595  ，动态添加移除数据源
```java
import com.baomidou.dynamic.datasource.DynamicRoutingDataSource;
import com.baomidou.dynamic.datasource.creator.DataSourceProperty;
import com.baomidou.dynamic.datasource.creator.DefaultDataSourceCreator;

@Service("DefaultDynamicDatasourceService")
public class DefaultDynamicDatasourceService implements IDynamicDatasource {
    @Autowired
    private DataSource dyDataSource;
    @Autowired
    private HikariDataSourceCreator hikariDataSourceCreator;

 @Override
    public void loadDynamicDatasource() {
        log.info("loadDynamicDatasource start time={}", DateUtil.getFormatNow("yyyy-MM-dd HH:mm:ss SSS"));

        List<DatasourceEntity> datasources = datasourceService.getAllDatasource();
        if (!datasources.isEmpty()) {
            datasources.forEach(dto -> {

                DataSourceProperty dataSourceProperty = new DataSourceProperty();
                BeanUtils.copyProperties(dto, dataSourceProperty, Constants.IGNORE_PROPERTIES);
                dataSourceProperty.setLazy(true);//3.4.0版本以下如果有此属性，需手动设置，不然会空指针。

                DynamicRoutingDataSource ds = (DynamicRoutingDataSource) dyDataSource;
                DataSource dataSource = hikariDataSourceCreator.createDataSource(dataSourceProperty);
                ds.addDataSource(dto.getDsName(), dataSource);

            });
        }
        log.info("loadDynamicDatasource end time={}", DateUtil.getFormatNow("yyyy-MM-dd HH:mm:ss SSS"));
    }

```
```yml
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源

      # hikari
      hikari:
        minimum-idle: 5
        maximum-pool-size: 15
        auto-commit: true
        idle-timeout: 30000
        max-lifetime: 1800000
        connection-timeout: 30000
#        connection-test-query: SELECT 1

      datasource:
        master:
          url: jdbc:h2:mem:testdb;MODE=MySQL
          driver-class-name:  # 3.2.0开始支持SPI可省略此配置
          type: com.zaxxer.hikari.HikariDataSource
          pool-name: "giveme5-h2"
```

Expected Result:
正常动态添加移除数据源

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

+ 无法注入 `private HikariDataSourceCreator hikariDataSourceCreator;`
```
Field hikariDataSourceCreator in cc.giveme5.common.datasource.DefaultDynamicDatasourceService required a bean of type 'com.baomidou.dynamic.datasource.creator.hikaricp.HikariDataSourceCreator' that could not be found.
```

+ 无法`DynamicRoutingDataSource ds = (DynamicRoutingDataSource) dyDataSource;`
```
Caused by: java.lang.ClassCastException: class com.zaxxer.hikari.HikariDataSource cannot be cast to class com.baomidou.dynamic.datasource.DynamicRoutingDataSource (com.zaxxer.hikari.HikariDataSource and com.baomidou.dynamic.datasource.DynamicRoutingDataSource are in unnamed module of loader 'app')

```
