### ISSUE TITLE
schema 初始化无效

### ISSUE THREAD

**Issue by mgzu** [baomidou/dynamic-datasource-spring-boot-starter#76]
# Enviroment

JDK Version(required): 
jdk1.8.0_181
SpringBoot Version(required): 
2.1.3.RELEASE
Starter Version(required):
2.5.5
# Describe
schema 无法初始化 mysql 5.7，长时间等待后，未创建表，且没有报错。
以下为配置信息
```
spring:
  datasource:
    dynamic:
      p6spy: false
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: FebsHikariCP
      primary: base
      datasource:
        base:
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/febs_base?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
          schema: sql/febs_base.sql
        quartz:
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/febs_quartz?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
          schema: sql/febs_quartz.sql
```
项目链接 https://github.com/mgzu/FEBS-Shiro
